#!/bin/bash
# mise description="Delete patch branch"
# mise alias=["delete-branch","deleb"]
# mise depends=["clean","git:branch:switch-master"]

git branch --list "patch*" | xargs -n 1 git branch -D

# vim:ft=bash
